name: 'SARIF Courier'
description: 'A GitHub Action to render SARIF Security Reports right into your Pull Requests. Without the need for GHAS support!'
author: ''

branding:
  icon: 'shield'
  color: 'green'

inputs:
  sarif_file:
    description: 'Path to the SARIF file to process.'
    required: true
    default: 'results.sarif'
  post_target:
    description: 'Where to post the results: "pr" for Pull Request comment, "issue" for Issue comment. If not set, the action will auto-detect based on the GitHub context.'
    required: false
    default: ''

outputs:
  result:
    description: 'Result of the SARIF processing.'

runs:
  using: 'node20'
  main: './dist/index.js'
